Algoritmo "ATV-23"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa da Silva
// Descrição   : Ler um valor e escrever se é positivo ou negativo
// Autor(a)    : Joao Pedro Gomes
// Data atual  : 31/08/2026
Var
   // Seção de Declarações das variáveis
   numero: inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um número :")
   Leia(numero)
   se numero >= 0 entao
      Escreval("Número digitado é positivo")
   senao
      Escreval("Número digitado é negativo")
   fimse

Fimalgoritmo