Algoritmo "ATV-17"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa da Silva
// Descrição   : Escreva um programa para ler o raio de um círculo, calcular e escrever a sua área.
// Autor(a)    : Joao Pedro Gomes
// Data atual  : 31/08/2026
Var
// Seção de Declarações das variáveis 
raio_circulo, calculo_final: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Calculadora - área do circulo")

Escreval("Infrome o valor do raio do circulo: ")
Leia(raio_circulo)

calculo_final <-  3.14 * (raio_circulo * raio_circulo)

Escreval("A área total do circulo é: ", calculo_final)

Fimalgoritmo