Algoritmo "ATV-15"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa da Silva
// Descrição   : Escreva um algoritmo para ler uma temperatura em graus Fahrenheit, calcular e escrever o valor
// correspondente em graus Celsius (baseado na fórmula abaixo)
// Autor(a)    : Joao Pedro Gomes
// Data atual  : 31/08/2026
Var
// Seção de Declarações das variáveis 
Celsius: real
Fahrenheit: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Conversor de Celsius para Fahrenheit")
Escreva("Digite o valor em Celsius: ")
Leia(Celsius)
Fahrenheit<-(9 * celsius + 160) / 5
Escreva("O valor em celsius convertido em Fahrenheit é: ", Fahrenheit)

Fimalgoritmo