Algoritmo "ATV-08"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa da Silva
// Descrição   :  Faça um algoritmo que converta metros para centímetros. Lembrando que 1m = 100cm.
// Autor(a)    : Joao Pedro Gomes
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
metros, resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Conversor de metros em centimetros")

Escreval("Digite o valor em metros: ")
Leia(metros)

resultado <- metros * 100


Escreval("Seu valor convertido para centimetros é:  ", resultado)

Fimalgoritmo