Algoritmo "ATV-05"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa da Silva
// Descrição   : Escreva um algoritmo para ler um valor (do teclado) e escrever (na tela) o seu antecessor.
// Autor(a)    : Joao Pedro Gomes
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis
numero01: Inteiro
antecessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Programa Antecessor")

Escreva("Digite o 1 número: ")
Leia(numero01)

antecessor <- numero01 - 1

escreva("A divisão dos números digitados é: ",antecessor)

Fimalgoritmo