Algoritmo "ATV-22"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa da Silva
// Descrição   : Ler um valor e escrever a mensagem É MAIOR QUE 10! se o valor lido for maior que 10, caso
// contrário, escrever NÃO É MAIOR QUE 10!
// Autor(a)    : Joao Pedro Gomes
// Data atual  : 31/08/2026
Var
   // Seção de Declarações das variáveis
   numero: inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um número :")
   Leia(numero)
   se numero > 10 entao
      Escreval("Número digitado é maior que 10")
   senao
      Escreval("Número digitado é menor que 10")
   fimse

Fimalgoritmo