Algoritmo "ATV-06"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa da Silva
// Descrição   : Escreva um algoritmo para ler as dimensões de um retângulo (base e altura), calcular e escrever a
// área do retângulo
// Autor(a)    : Joao Pedro Gomes
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis
alt, bs, resultado: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Calculadora da área do retângulo")

Escreval("Digite o valor da altura:")
Leia(alt)

Escreval("Digite o valor da base:")
Leia(bs)

resultado <- alt * bs

Escreval("A área total do retângulo é: ", resultado)

Fimalgoritmo