Algoritmo "ATV-A"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaja
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Joao Pedro Gomes
// Data atual  : 10/09/2026
Var
   // Seção de Declarações das variáveis
   i: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   i <- 15
   repita
      escreval(i * i)
      i<- i + 1
   ate i > 200
Fimalgoritmo
