Algoritmo "ATV-A"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa da Silva
// Descrição   : Escreva um algoritmo para ler as dimensões de um retângulo (base e altura), calcular e escrever a
// área do retângulo
// Autor(a)    : Joao Pedro Gomes
// Data atual  : 31/08/2026
Var
// Seção de Declarações das variáveis 
Celsius: real
Fahrenheit: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Conversor de Celsius para Fahrenheit")
Escreva("Digite o valor em Celsius: ")
Leia(Celsius)
Fahrenheit<-(9 * celsius + 160) / 5
Escreva("O valor em celsius convertido em Fahrenheit é", Fahrenheit)

Fimalgoritmo